channels:
- conda-forge
- defaults
dependencies:
- asn1crypto=0.22.0=py36_0
- beautifulsoup4=4.6.0=py36_0
- blinker=1.4=py36_0
- ca-certificates=2017.7.27.1=0
- certifi=2017.7.27.1=py36_0
- cffi=1.10.0=py36_0
- chardet=3.0.4=py36_0
- click=6.7=py36_0
- cryptography=2.0.3=py36_0
- flask=0.12.2=py36_0
- flask-login=0.4.0=py36_0
- flask-oauthlib=0.9.4=py36_0
- flask-socketio=2.9.2=py36_0
- flask-sqlalchemy=2.3.2=py_0
- flask-wtf=0.14.2=py36_0
- future=0.16.0=py36_1
- gevent=1.2.2=py36_0
- gevent-websocket=0.10.1=py36_0
- greenlet=0.4.12=py36_0
- idna=2.6=py36_1
- itsdangerous=0.24=py_2
- jinja2=2.9.6=py36_0
- json-rpc=1.10.3=py36_0
- libffi=3.2.1=3
- libsodium=1.0.10=0
- markupsafe=1.0=py36_0
- msgpack-python=0.4.8=py36_0
- ncurses=5.9=10
- oauthlib=2.0.6=py_0
- openssl=1.0.2l=0
- pip=9.0.1=py36_0
- pycparser=2.18=py36_0
- pyjwt=1.5.3=py_0
- pyopenssl=17.2.0=py36_0
- pysocks=1.6.7=py36_0
- python=3.6.3=0
- python-engineio=1.7.0=py36_0
- python-socketio=1.8.1=py_0
- pyzmq=16.0.2=py36_0
- readline=6.2=0
- requests=2.18.4=py36_1
- requests-oauthlib=0.8.0=py36_1
- setuptools=36.6.0=py36_1
- six=1.11.0=py36_1
- sqlalchemy=1.1.13=py36_0
- sqlite=3.13.0=1
- tk=8.5.19=2
- urllib3=1.22=py36_0
- werkzeug=0.12.2=py_1
- wheel=0.30.0=py_1
- wtforms=2.1=py36_0
- xz=5.2.3=0
- zeromq=4.1.5=0
- zlib=1.2.8=3
- pip:
  - zerorpc==0.6.1
